apiVersion: v1
kind: Service
metadata:
  labels:
    app: java-exam-deploy
  name: java_service
spec:
  ports:
  - port: 8001
    protocol: TCP
    targetPort: 8080
  selector:
    app: java-exam-deploy
status:
  loadBalancer: {}
